[package]
name = "bowtie-rust-boon"
version = "0.1.0"
edition = "2021"

[dependencies]
boon = "0.5"
serde_json = "1"
os_info = "3.8.0"
rustc_version = "0.4.0"

[build-dependencies]
cargo-lock = "9.0"
