name: Build and Publish Versioned Images

on:
  workflow_dispatch:
    inputs:
      implementation:
        description: "The implementation name whose multiple versions to build for."
        required: true
        type: string

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-versions-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: image-versions-matrix
        run: |
          MATRIX="[]"
          implementation=${{ github.event.inputs.implementation }}
          if [ -f "implementations/$implementation/matrix-versions.json" ]; then
            versions=$(cat "implementations/$implementation/matrix-versions.json")
            MATRIX=$(echo $MATRIX | jq --arg impl "$implementation" --argjson vers "$versions" '. + [{"image": $impl, "version": $vers[]}]')
          else
            MATRIX=$(echo $MATRIX | jq --arg impl "$impl" '. + [{"image": $impl, "version": "latest"}]')
          fi
          echo "matrix=$(echo $MATRIX | jq -c .)" >> $GITHUB_OUTPUT

  build-image:
    needs: list
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.list.outputs.images) }}
    uses: ./.github/workflows/images.yml
    with:
      image: ${{ matrix.image }}
      version: ${{ matrix.version }}
